### ISSUE TITLE
Struggling with basic connection

### ISSUE THREAD

**Issue by laktosterror** [caius/spacelift-tailscale#9]
Hi,

I'm trying to set up the runner image on spacelift but I can't seem to connect to any hosts on my tailnet. Terraform times out.

Running ping or curl times out, tried directly against IP of a tailscale machine and against a subnet machine (with TS_EXTRA_ARGS set to --accept-routes).
 
No luck.

Running spacelift task "tailscale status" does list my tailscale machines though. 

Log file coming!

**Comment by laktosterror** [comment]
https://pastebin.com/Q5agQL0s

**Comment by caius** [comment]
Hey,

Looks like your tailscaled is coming up successfully from the logs, I can't remember offhand if running as userspace networking sets up any routing for it. I suspect from the logs and `tailscale status` being successful it doesn't.

You could try `tailscale ping <ip>` instead to verify connectivity, that knows to go via the tailnet regardless of the local route table.

If you want routing for networking tools to function you'd need to add the route yourself I think. Using `TS_EXTRA_ARGS=--ssh` to login and have a look around is the easiest way to figure it out I've found - quicker than using a task run!

Our use case was to reach a webserver over the tailnet, and the api wrapper (terraform provider) understands how to use a HTTP Proxy which is provided by `tailscaled` in this image. If you've tried setting `http_proxy= http://localhost:8080` and the terraform provider isn't using the HTTP Proxy, I'd suggest trying `ALL_PROXY=localhost:1080` to use SOCKS proxy instead. Depends if the provider supports HTTP or SOCKS proxying though.

What are you trying to talk to from terraform out of interest?

**Comment by laktosterror** [comment]
Hi again, thanks for your reply!

tailscale ping works, good tip!

i saw now that i missed putting http:// before ip when i tried curling. 
Now i can curl webserver on remote subnets when --accept-routes is set. This is with HTTP_PROXY set ofc.

Im trying to access a proxmox server. 
Im using this provider which doesnt mention any support for proxy, so the problem is might be there.

https://registry.terraform.io/providers/bpg/proxmox/0.42.1

Also seems like some modules use SSH, so i might be out of luck anyway.
Just wanted to stay on spacelift and not go back to terraform cloud just to access the self hosted runner they allow (business license required at spacelift). Its nice being able to use ansible and terraform from the same place :)

**Comment by caius** [comment]
Looks like that provider is using Golang's `net/http` which should pick up `http_proxy` from the environment, same as curl does: https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmox/api/client.go#L17 Any HTTP API requests to Proxmox _should_ just work I think, that's how we're using the Nomad and Vault providers in terraform, the underlying library is Golang's `net/http` which automatically reads from the environment for proxy configuration.

Not sure about the SSH client if you're using that part of the provider though, a quick google suggests it might need explicit proxy support adding (https://stackoverflow.com/a/48266458) as I can't see any logic in https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmox/ssh/client.go to add proxying support for SSH.

**Comment by caius** [comment]
From some more googling I've found a [CircleCI Orb that provides tailscale](https://circleci.com/developer/orbs/orb/motivaventures/circleci-tailscale) in the same way, and also includes [proxychains](https://github.com/haad/proxychains) which I've not come across before, looks like it would solve your problem by forcing the SSH connection to SOCKS proxy via tailscaled.

I'll look at getting it added to the image as that provides more flexibility in using it, then you'd need to change your terraform command to be `proxychain terraform <args>` from reading the docs.

**Comment by caius** [comment]
Thinking about it some more @laktosterror, I wonder if you can use SSH's `ProxyCommand` through the config file to get the proxmox provider to lean on the socks proxy without needing proxychain in the image. (I'm also unsure off the top of my head if SSH uses TCP out the box or not - if it uses UDP then proxychain won't work anyway.)

You could try something like this in your spacelift environment, see if the proxmox provider picks it up. Probably needs to go in `/home/spacelift/.ssh/config` which likely doesn't exist already, you'll probably need to mount the file from a context, then have a `before_init` set to copy it into place (and likely mkdir the `.ssh` path first.):

```
Host *
  ProxyCommand nc -X connect -x localhost:1080 %h %p
```

**Comment by laktosterror** [comment]
Hey great findings!

Just skimmed thru https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmox/ssh/client.go

And on line 297, there's a unfortunate message: 
“NOTE: configurations in ~/.ssh/config are not considered by golang's ssh implementation”

Found a go package that looks like it could help, but I suppose I'll have to ask the provider dev nicely.
https://pkg.go.dev/github.com/kevinburke/ssh_config


According to this tailscale blog post, ssh over tailnet looks to be possible from inside a GitHub action. 
Check last step in task example:
https://tailscale.com/blog/2021-05-github-actions-and-tailscale

Looking at the tailscale action I can't see that they are doing anything special besides running tailscale with sudo?
https://github.com/tailscale/github-action

Maybe this just works because GitHub runs actions in VMs.


Proxychain looks promising!

**Comment by laktosterror** [comment]
Some news @caius.

I could not get `ProxyCommand` to work. The version of `nc` provided in Alpine linux don't seem to support the -X flag.
Creating a custom workflow in Spacelift prepending all terraform commands with `proxychains` did actually work for the Proxmox providers http calls, but sadly not for the ssh connection.


I did however get it to work using `proxyChains` to first create a SSH connection to my Proxmox host (over tailscales using the socks5 server) and forward local ports 18006 and 10022 inside the Spacelift container to remote Proxmox ports 8006 and 22, using [SSH tunneling](https://linuxize.com/post/how-to-setup-ssh-tunneling/).

Then i configured the terraform provider to point to `localhost` instead of my Proxmox IP and used the forwarded ports 18006 and 10022, instead of remote ports 8006 and 22.

terraform->localhost:18006+10022->SSH tunnel->tailscale socks5-> proxmox-ip:8006+22


Here's what i did.
1. Mount `proxychains.conf` file via Spacelift context. With content:
	```
	[ProxyList]
	socks5  127.0.0.1 1080
	```
2. Mount ssh keyfile ex. `rsa.key` via Spacelift context (Private ssh key to access Proxmox).

4. Adjust stack config and add `chmod ...` + `proxychains ...` to your before hooks for plan, apply and destroy.
   `before_plan` example:

	```yaml
	stacks:
	  proxmox:
	    runner_image: "ghcr.io/caius/spacelift-tailscale:latest"
	    before_plan:
	      - "spacetail up"
	      - "trap 'spacetail down' EXIT"
	      - "chmod 600 /mnt/workspace/source/rsa.key"
	      - "proxychains -f <path-to-proxychains.conf> ssh -i <path-to-rsa.key> -o StrictHostKeyChecking=accept-new -fN -L 18006:<proxmox-ip>:8006 -L 10022:<proxmox-ip>:22 root@<proxmox-ip>"
	```
	`StrictHostKeyChecking=accept-new` auto adds proxmox public key to known_hosts. Without this it prompts for a yes or no.
	`-fN` runs ssh tunnel and port forwards in the bakground. 

	Not tested but you should be able replace `<proxmox-ip>` with Proxmox tailscale ip.
	I used subnet routed ip and set required env variable `TS_EXTRA_ARGS=--accept-routes`.

5. Configure proxmox terraform provider, example:
   ```terraform
   provider "proxmox" {
     endpoint = "https://localhost:18006"
     username = var.virtual_environment_username
     password = var.virtual_environment_password
     insecure = true
     ssh {
       node {
          name    = "first-node"
          address = "localhost"
          port    = "10022"
       }
     }
   }
   ```

Thanks for all your help so far! Glad to get it working finally.

Cheers

**Comment by caius** [comment]
Opened #10 for including proxychains-ng in the image, but going to close this issue as you got it worked. Thanks for replying with your working solution 😄
